- name: Install requirements
  apt:
    name: openjdk-8-jre-headless
    state: present

- name: Download and Unpack JMeter
  unarchive:
    src: "http://mirror.cogentco.com/pub/apache/jmeter/binaries/apache-jmeter-3.3.tgz"
    dest: /srv/
    creates: /srv/apache-jmeter-3.1/LICENSE
    mode: "u=rwX,g=rwX,o=rX"
    remote_src: yes
